import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "./components/(Navigation)/Navigation";

export const metadata: Metadata = {
  title: "Comissão de Festas das Mós",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className= {`${montserrat.variable} antialiased flex`}
      >
        <Navigation />
        <div className="flex flex-col w-full h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
